### ISSUE TITLE
Not Capturing iframs and video tag 

### ISSUE THREAD

**Issue by drvekariya6** [SachinGanesh/screenshot#101]

**Comment by drvekariya6** [comment]
While i am using  flutterhtml widget  and tack a screen shot ,not capturing ifram or video tag in screenshort ..countine showing black screen or widget

**Comment by DanteAlucard98** [comment]
i have the same issue u.u

**Comment by ritheshSalyan** [comment]
https://github.com/SachinGanesh/screenshot/issues/62  Due to this, we cannot capture platform views.

**Comment by ritheshSalyan** [comment]
Closing in favour of https://github.com/SachinGanesh/screenshot/issues/62 If you think this is incorrect please feel free to reopen.
