### ISSUE TITLE
[flutter_unity_widget] Blank image screenshot ([ERROR:flutter/flow/layers/platform_view_layer.cc(20)])

### ISSUE THREAD

**Issue by RoyalCoder88** [SachinGanesh/screenshot#106]
Hi I'm using **flutter_unity_widget** I'm trying to take a screenshot of the Unity widget but I get this error:

`
[ERROR:flutter/flow/layers/platform_view_layer.cc(20)] Trying to embed a platform view but the PrerollContext does not support embedding

`

Please guide me how to fix this issue, thanks in advance!

**Comment by ritheshSalyan** [comment]
hello @RoyalCoder88 , ```flutter_unity_widget``` is a Platform view, We cannot capture platform views, Please check this #62
