### ISSUE TITLE
No MediaQuery ancestor could be found 

### ISSUE THREAD

**Issue by yichaosun** [SachinGanesh/screenshot#110]
Hi,Dear

I got this Exception
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building CircleAvatar(dirty):
No MediaQuery widget ancestor found.
```
when I want share img came from captureFromWidget
```dart
              screenshotController
                  .captureFromWidget(sharedCard,
                      delay: Duration(milliseconds: 10),
                  pixelRatio:1.5)
                  .then((capturedImage) async {
                ShowCapturedWidget(context, capturedImage!);
              }).catchError((onError) {
                print(onError);
              });
            },
```

which means ,the widge named CircleAvatar( contained by shardCard here), have no MediaQuery ancestor, sure it is!

what I want to do ,is capturing widget (card) with some message, to share with people and add the message( who I am ,from which app), seems reasonable, ha

so , sharedCard is a container contains card which visible  and some text which not visible, so I used captureFromWidget

as we see the Exception, there needs a MediaQuery ancestor ,how can I handle this? to warp shareCard with MetariaApp?

**Comment by yichaosun** [comment]
add:

I just use capture(card), there is no Exception

**Comment by Johnny-sel** [comment]
`                                  final widget= MediaQuery(
                                    data: MediaQueryData(
                                      size: MediaQuery.of(context).size
                                    ),
                                    child: MyWidget())
`

**Comment by yichaosun** [comment]
> final widget = MediaQuery(
>                                 data: MediaQueryData(size: MediaQuery.of(context).size),
>                                 child: MyWidget()
>                               );
> 
>                             final screenshot = await screenshotController.captureFromWidget(widget);
>                             final createFile = await File('$selectedDirectory/screenshot.png').create();
>                             await createFile.writeAsBytes(screenshot);

means wrap my sharedCard in MediaQuery?

**Comment by yichaosun** [comment]
> final widget = MediaQuery(
>                                 data: MediaQueryData(size: MediaQuery.of(context).size),
>                                 child: MyWidget()
>                               );
> 
>                             final screenshot = await screenshotController.captureFromWidget(widget);
>                             final createFile = await File('$selectedDirectory/screenshot.png').create();
>                             await createFile.writeAsBytes(screenshot);

thx, so much,it's did work!

**Comment by yichaosun** [comment]
https://github.com/SachinGanesh/screenshot/issues/112

hi bro @Johnny-sel ,how about seeing this question? we need you!
