### ISSUE TITLE
Unable to capture camera view

### ISSUE THREAD

**Issue by carl0529** [SachinGanesh/screenshot#113]
I wonder if it is intentional due to privacy concern or permission update, but I fail to capture CameraPreview. I am trying to mirror the full screen from an Android phone to webpage, only successful on mirroring every widget but not CameraPreview itself. I had try even directly capturing the CameraPreview only, but it still only give a pure white background.  Thanks for your kind notice.

<img width="721" alt="Screenshot 2022-08-05 153211" src="https://user-images.githubusercontent.com/47996588/183026130-fca49b1f-c64d-4823-afde-10ffd6d1855c.png">

**Comment by ritheshSalyan** [comment]
We cannot Capture Platform Views. Closing in favour of [This issue](https://github.com/SachinGanesh/screenshot/issues/62)
