### ISSUE TITLE
when i click add button, throw an error

### ISSUE THREAD

**Issue by fightingLT** [SachinGanesh/screenshot#12]
W/System.err(25434): java.io.FileNotFoundException: /storage/emulated/0/example/1572487834458.png (No such file or directory)
W/System.err(25434):    at java.io.FileOutputStream.open0(Native Method)
W/System.err(25434):    at java.io.FileOutputStream.open(FileOutputStream.java:308)
W/System.err(25434):    at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
W/System.err(25434):    at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
W/System.err(25434):    at com.example.imagegallerysaver.ImageGallerySaverPlugin.saveImageToGallery(ImageGallerySaverPlugin.kt:61)
W/System.err(25434):    at com.example.imagegallerysaver.ImageGallerySaverPlugin.onMethodCall(ImageGallerySaverPlugin.kt:33)
W/System.err(25434):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
W/System.err(25434):    at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
W/System.err(25434):    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
W/System.err(25434):    at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(25434):    at android.os.MessageQueue.next(MessageQueue.java:332)
W/System.err(25434):    at android.os.Looper.loop(Looper.java:168)
W/System.err(25434):    at android.app.ActivityThread.main(ActivityThread.java:6867)
W/System.err(25434):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(25434):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
W/System.err(25434):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

platform: android
android version: 9.1
flutter doctor: 
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.14.5 18F132, locale en-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.39.1)
[✓] Connected device (1 available)

**Comment by SachinGanesh** [comment]
Please Give Storage Permission to the app.
