### ISSUE TITLE
can't use in isolate

### ISSUE THREAD

**Issue by SpirikleOfficial** [SachinGanesh/screenshot#120]
Hi,
I wanted to capture invisible widgets in multiple isolates but I can't seem to use this package for the same. Please look into this, thank you.

**Comment by ritheshSalyan** [comment]
Hello @SpirikleOfficial , 

  Unfortunately, you cannot do any UI actions in isolates. Please check this issue [https://github.com/flutter/flutter/issues/10647](https://github.com/flutter/flutter/issues/10647), Due to this capturing widgets from isolate is not possible now.

**Comment by spauldhaliwal** [comment]
One should be able to achieve this using a package like [flutter_isolate](https://pub.dev/packages/flutter_isolate). I believe it creates a new flutter engine which is able to run ui actions. I haven't tried it, but I was able to use this plugin in the [work_manager](https://pub.dev/packages/workmanager) plugin, which I think uses a similar mechanism to flutter_isolate.
