### ISSUE TITLE
Remove redundant generic type on Screenshot widget

### ISSUE THREAD

**Issue by michasng** [SachinGanesh/screenshot#125]
Screenshot is declared as Screenshot\<T\>, with no explanation or use of T.
Please remove the generic type.

https://github.com/SachinGanesh/screenshot/blob/e6165a8fd785ec69882766927094104121b6c84e/lib/screenshot.dart#L261

**Comment by ritheshSalyan** [comment]
We have removed the generic type. so Closing this issue
