### ISSUE TITLE
No named parameter with the name 'window'. Error

### ISSUE THREAD

**Issue by venky9885** [SachinGanesh/screenshot#127]
AppData/Local/Pub/Cache/hosted/pub.dev/screenshot-1.3.0/lib/screenshot.dart:160:7: Error: No named parameter with the name 'window'.
      window: ui.window,
      ^^^^^^

**Comment by venky9885** [comment]
i am using flutter beta latest version ,Please solve it asap

**Comment by foresourcedev** [comment]
Same problem, same urgency.

Flutter 3.10.0-1.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision ecdb7841df (7 days ago) • 2023-04-11 20:47:40 -0700
Engine • revision 870e640e7e
Tools • Dart 3.0.0 (build 3.0.0-417.1.beta) • DevTools 2.23.1

**Comment by Khaoz-Topsy** [comment]
I have the same issue, I have created a PR that is hopefully good enough to be merged 😅. For now, you can get around this issue by using my forked git repo (you will be dependent on me keeping the repo public & available). Add this to your `pubspec.yaml`:

```
  screenshot:
    git:
      url: https://github.com/AssistantApps/screenshot
      ref: master
```

I take no responsibility for any new bugs I introduced with my small changes 😅

**Comment by foresourcedev** [comment]
Thank you!

**Comment by uzuki-P** [comment]
Now it's broken on release version since flutter is upgraded to 3.10.0
 
```
Running Gradle task 'assembleStagingDebug'...
../../../.pub-cache/hosted/pub.dev/screenshot-1.3.0/lib/screenshot.dart:160:7: Error: No named parameter with the name 'window'.
      window: ui.window,
      ^^^^^^
../../sdk/flutter/packages/flutter/lib/src/rendering/view.dart:68:3: Context: Found this candidate, but the arguments don't match.
  RenderView({
  ^^^^^^^^^^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-arm64, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2023.1.1)
[✓] VS Code (version 1.78.1)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 1 category.
```
