### ISSUE TITLE
Is possible screenshot all a ListView.builder? 

### ISSUE THREAD

**Issue by laguierre** [SachinGanesh/screenshot#131]
I am trying to take screenshot of all a ListView.builder widget, is finite (top 35 elements).
My tree is:
```
Screeshot(
controller: screenshotController,
child: Column(
children: [
  Containers1,
  Containers2,
  Expaded(
     ListView.builder(...)),
])
```
I could save a file... but only of the side of the screen. I tried wrap with SingleScroll... but result is the same.
Any help is appreciated. Thx

**Comment by laguierre** [comment]
I used "targetSize" with a multiple of the height of the screen.

**Comment by AWarmHug** [comment]
You can consider using [widget_screenshot](https://pub.dev/packages/widget_screenshot),this support long screenshot

**Comment by laguierre** [comment]
Interesting Package! However I same some issue becuase my ignorance in flutter. You could see it's scrolling with the current listview size, however it's repeat the my custom app bar.
My widget tree now is:
```
WidgetShot(
key: shotKey,
child: Column(
children: [
 CustomAppBar(),
 Container1(),
 Container2(),
 Expaded(
     ListView.builder(
         controller: scrollController
     ...)
]))
....
onPress(){
            WidgetShotRenderRepaintBoundary repaintBoundary =
            shotKey.currentContext!.findRenderObject() as WidgetShotRenderRepaintBoundary;
            var resultImage = await repaintBoundary.screenshot(
                scrollController: scrollController,
                backgroundColor: Colors.blue,
                format: ShotFormat.png,
                pixelRatio: 1);
}
```
Do you have any idea? Issue between key posicion and scroll controller?
![2023-05-11 23_02_04 802101](https://github.com/SachinGanesh/screenshot/assets/84541098/003911b0-9319-446c-a7ed-741fd7654c96)
and using screenshot Widget
![EM'TEST'_2023-05-11T20-34-59-894282 - copia](https://github.com/SachinGanesh/screenshot/assets/84541098/099ba709-a7b4-4e9e-b385-8122cc89ead0)

**Comment by AWarmHug** [comment]
try `widget_screenshot: ^0.0.5` and example

**Comment by AWarmHug** [comment]
try new version and example

**Comment by laguierre** [comment]
I have implemented the new version, it is ok. Attached screenshot. Two observations to review:
- Please see the black line that limits the height of the screen on the images.
- A double check on "format: ShotFormat...". In JPG mode it seems that it is saved as PNG.
You have really done an excellent job!
![2023-05-13 20_57_23 828634](https://github.com/SachinGanesh/screenshot/assets/84541098/133b98c2-092d-4da4-a309-f0246d8793ca)
![2023-05-13 21_03_06 997405](https://github.com/SachinGanesh/screenshot/assets/84541098/b4a1703d-685b-4a27-8f2a-35dc5f453f16)

**Comment by AWarmHug** [comment]
> I have implemented the new version, it is ok. Attached screenshot. Two observations to review:
> 
> * Please see the black line that limits the height of the screen on the images.
> * A double check on "format: ShotFormat...". In JPG mode it seems that it is saved as PNG.
>   You have really done an excellent job!
>   ![2023-05-13 20_57_23 828634](https://user-images.githubusercontent.com/84541098/238156957-133b98c2-092d-4da4-a309-f0246d8793ca.png)
>   ![2023-05-13 21_03_06 997405](https://user-images.githubusercontent.com/84541098/238157370-b4a1703d-685b-4a27-8f2a-35dc5f453f16.png)

* I try exmple like your ui, but no line, Can you provide some test code？
* about ShotFormat, maybe you didn't modify `path.png` to `path.jpeg`,this just path, "否" is no
![no_png](https://github.com/SachinGanesh/screenshot/assets/18473359/e5200bc1-1b3a-4dfd-9478-99c72de58593)

**Comment by AWarmHug** [comment]
> I have implemented the new version, it is ok. Attached screenshot. Two observations to review:
> 
> * Please see the black line that limits the height of the screen on the images.
> * A double check on "format: ShotFormat...". In JPG mode it seems that it is saved as PNG.
>   You have really done an excellent job!
>   ![2023-05-13 20_57_23 828634](https://user-images.githubusercontent.com/84541098/238156957-133b98c2-092d-4da4-a309-f0246d8793ca.png)
>   ![2023-05-13 21_03_06 997405](https://user-images.githubusercontent.com/84541098/238157370-b4a1703d-685b-4a27-8f2a-35dc5f453f16.png)

* I try exmple like your ui, but no line, Can you provide some test code？
* about ShotFormat:
if cannot scroll,I use Flutter's canves, the resulting image can only be PNG,because [Flutter only supports PNG](https://github.com/flutter/flutter/issues/94026),the [image](https://pub.dev/packages/image) pub can convert png to jpeg
,else maybe you didn't modify path.png to path.jpeg, just a path, "否" is no
![截屏2023-05-14 11 58 20](https://github.com/SachinGanesh/screenshot/assets/18473359/e12c38af-ae63-42a0-9134-de9374216d51)

**Comment by laguierre** [comment]
I tested in a physical phone instead of a AVD (Pixel 4 API 30) and there is no line, it's all ok. I don't know why...
If you need to test other things, please let me know
