### ISSUE TITLE
Make screenshot of the 3d scene

### ISSUE THREAD

**Issue by hellhorse123** [SachinGanesh/screenshot#133]
I'm trying to take a screenshot from BabylonJSViewer (babylonjs_viewer.dart) using the screenshot.dart library and on the iPhone simulator it takes a photo of only a white screen (on Android everything is fine):

```
 Screenshot(
                    controller: _screenshotController,
                    child: BabylonJSViewer(src: mannequinLink)),
```
.
I also get errors:

```
 [VERBOSE-2:platform_view_layer.cc(19)] Trying to embed a platform view but the PrerollContext does not support embedding
[VERBOSE-2:platform_view_layer.cc(38)] Trying to embed a platform view but the PaintContext does not support embedding
```
although adding the necessary line to info.plst :

```
<key>io.flutter.embedded_views_preview</key>
	<true/>
```

Can Screenshot take screenshots of 3D scenes?

**Comment by ritheshSalyan** [comment]
https://github.com/SachinGanesh/screenshot/issues/62

Currently, We cannot capture screenshot Platform views. 

Closing this issue in favour of #62, If you think it is incorrect please feel free to reopen.
