### ISSUE TITLE
ScreenShot from video_player

### ISSUE THREAD

**Issue by salime45** [SachinGanesh/screenshot#14]
Hi,

I am using this lib and the https://pub.dev/packages/video_player, but seems dont work correctly.

The generate image is always black, anyone knows how to fix this?

Thanks

**Comment by salime45** [comment]
I leave here a repo with the problem https://github.com/salime45/video_screenshot

**Comment by Cerya** [comment]
> I leave here a repo with the problem https://github.com/salime45/video_screenshot

i have the same problem, Have you found a solution?

**Comment by zzterrozz** [comment]
Any update please ?

**Comment by kzrfaisal** [comment]
Having the same issue, no help yet.

**Comment by kzrfaisal** [comment]
Has anyone found the solution ?

**Comment by ritheshSalyan** [comment]
Video player is using platform view to render video.  taking screen shot of that is not possible because of [https://github.com/flutter/flutter/issues/25306](https://github.com/flutter/flutter/issues/25306)

**Comment by ritheshSalyan** [comment]
Closing in favour of https://github.com/SachinGanesh/screenshot/issues/62
