### ISSUE TITLE
No named parameter with the name 'view'.

### ISSUE THREAD

**Issue by iamsannyrai** [SachinGanesh/screenshot#141]
screenshot version 2.0.0
<img width="1136" alt="Screenshot 2023-05-13 at 2 53 06 PM" src="https://github.com/SachinGanesh/screenshot/assets/50624619/2a636a46-e2b1-44c3-90d3-168607529d44">
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (4 weeks ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1

**Comment by ritheshSalyan** [comment]
Hello @iamsannyrai ,

`screenshot: 2.0.0` is a migration to latest `FlutterView` from `ui.window`. This is supported in flutter version `3.10`. If you are using flutter below `3.10` please consider using `screenshot: 1.3.0`. 

I am closing this issue. If you think that is incorrect please feel free to reopen.

Thank you,
