### ISSUE TITLE
No named parameter with the name 'window'

### ISSUE THREAD

**Issue by almogtovim** [SachinGanesh/screenshot#142]
Hello,

I just upgraded Flutter to 3.10.0 version and it seems like there is a new issue with screenshot 2.0.0.
The error: 

>  Error: No named parameter with the name 'window'.
> screenshot.dart:160
>       window: ui.window,
>       ^^^^^^
> : Context: Found this candidate, but the arguments don't match.
> view.dart:68
>   RenderView({
>   ^^^^^^^^^^
> 
> Target kernel_snapshot failed: Exception

Running flutter doctor -v:

> 
> [✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-arm64, locale en-IL)
>     • Flutter version 3.10.0 on channel stable at /Users/almogtovim/Development/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 84a1e904f4 (5 days ago), 2023-05-09 07:41:44 -0700
>     • Engine revision d44b5a94c9
>     • Dart version 3.0.0
>     • DevTools version 2.23.1
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
>     • Android SDK at /Users/almogtovim/Library/Android/sdk
>     • Platform android-33, build-tools 33.0.0
>     • ANDROID_HOME = /Users/almogtovim/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 14.2)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Build 14C18
>     • CocoaPods version 1.12.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2021.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
> 
> [✓] VS Code (version 1.78.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.64.0
> 
> [✓] Connected device (4 available)
>     • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 32) (emulator)
>     • iPhone 12 mini (mobile)     • 4063570F-0E57-4AB8-9902-09EEBDB3A83E • ios            •
>       com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
>     • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.3.1 22E772610a
>       darwin-arm64
>     • Chrome (web)                • chrome                               • web-javascript • Google Chrome 113.0.5672.92
> 
> [✓] Network resources
>     • All expected network resources are available.
>

**Comment by ritheshSalyan** [comment]
hello @almogtovim ,

It looks like your project is using `screenshot: 1.3.0`. Can you please follow these steps and retry:
1. Confirm that in your `pubspec.yaml` has `screenshot: 2.0.0` added to your dependency list.
2. Delete `pubspec.lock` , and run `flutter clean`.
3. Now please running your project after `flutter pub get`
