### ISSUE TITLE
No named parameter with the name 'view'.

### ISSUE THREAD

**Issue by prifyDevelopers** [SachinGanesh/screenshot#147]
I got this error after upgrading to version 2.0.0 ,it works fine on ios though

../AppData/Local/Pub/Cache/hosted/pub.dev/screenshot-2.0.0/lib/screenshot.dart:154:42: Error: Undefined name 'View'.
        context == null ? fallBackView : View.maybeOf(context) ?? fallBackView;
                                         ^^^^
../AppData/Local/Pub/Cache/hosted/pub.dev/screenshot-2.0.0/lib/screenshot.dart:164:7: Error: No named parameter with the name 'view'.
      view: view,
      ^^^^
../Downloads/flutter_windows_3.7.1-stable/flutter/packages/flutter/lib/src/rendering/view.dart:68:3: Context: Found this candidate, but the arguments don't match.
  RenderView({
  ^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Super-S\Downloads\flutter_windows_3.7.1-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1151

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\Super-S\Downloads\flutter_windows_3.7.1-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

**Comment by sharmaAshish-dev** [comment]
I'm having the same problem, did you found anything to solve this issue? if so, please let me know.

**Comment by ritheshSalyan** [comment]
Hello @sharmaAshish-dev , 
       `screenshot 2.0.0` or above version will work only with flutter above `3.10`. You are trying to use the latest version of the screenshot with Flutter `3.7`. Please use a lower version of the `screenshot` plugin or upgrade your flutter to `3.10`
