### ISSUE TITLE
Black screen on Youtube screenshot

### ISSUE THREAD

**Issue by minh-dai** [SachinGanesh/screenshot#148]
I am trying to take a screenshot of YoutubePlayer and then save it into the gallery
But the image is a Black image.

This is my code: 
Screenshot(
          controller: screenshotController,
          child: YoutubePlayer(
            controller: _controller,
            showVideoProgressIndicator: true,
          ),
        )

**Comment by Trung15010802** [comment]
Same for me

**Comment by minh-dai** [comment]
@Trung15010802 Trun
This library is not support 
https://github.com/flutter/flutter/issues/83856

**Comment by Trung15010802** [comment]
> @Trung15010802 Trun
> This library is not support 
> https://github.com/flutter/flutter/issues/83856

Thanks for letting me know. Do you any way to achieve that. Thank you very much

**Comment by ritheshSalyan** [comment]
https://github.com/SachinGanesh/screenshot/issues/62

Currently, We cannot capture screenshot Platform views. 

Closing this issue in favour of #62, If you think it is incorrect please feel free to reopen.
