### ISSUE TITLE
Undefined name 'View'.

### ISSUE THREAD

**Issue by theeranan** [SachinGanesh/screenshot#150]
how fix error after import 

screenshot-2.0.0/lib/s
creenshot.dart:154:42: Error: Undefined name 'View'.
        context == null ? fallBackView : View.maybeOf(context) ??
        fallBackView;
        
i'm use sdk version 
environment:
  sdk: '>=2.12.0 <3.0.0'

**Comment by UmairSaqibBhutta** [comment]
update your Flutter sdk version to 3.10

**Comment by ritheshSalyan** [comment]
Hi,
If you are using a non-null safety version then please use package version `1.3.0`. Package version from `2.0.0` supports only flutter ` >=3.10`
Hope this helps.

Closing the issue. If you think it is incorrect Please reopen issue.
