### ISSUE TITLE
Requested the Locale of a context that does not include a Localizations ancestor.

### ISSUE THREAD

**Issue by tuceturan** [SachinGanesh/screenshot#151]
When I use captureFromWidget function ıt throws error 

Requested the Locale of a context that does not include a Localizations ancestor.

To request the Locale, the context used to retrieve the Localizations widget must be that of a widget that is a descendant of a Localizations widget.

Can you help?

**Comment by agilerdev** [comment]
Did you find any workaround?

**Comment by ritheshSalyan** [comment]
@tuceturan , You can Wrap your widget with localization and then capture screenshot.
Hope it helps.

Closing this issue. If you think it is incorrect please reopen the issue.
