### ISSUE TITLE
No MediaQuery widget ancestor found.

### ISSUE THREAD

**Issue by niluved** [SachinGanesh/screenshot#159]
I'm trying to use the captureFromLongWidget method to capture a List of widgets as described in the docs but i'm getting the following error in my console.

"The following assertion was thrown building Builder(dirty):
No MediaQuery widget ancestor found.
Builder widgets require a MediaQuery widget ancestor.
The specific widget that could not find a MediaQuery ancestor was:
Builder"

I wrapped myLongWidget  inside a Builder widget as the docs show and i'm initializing it in initState method:

void initState() {
    super.initState(); 
    widgetsNodes = MazeWidgetMethods.getWidgetsFromMaze(widget.mazeComplete, context);
    parentText = MazeWidgetMethods.getFirstSubtopicText(widget.mazeComplete, context);

    myLongWidget = Builder(
        builder: (context) => SizedBox(
              height: MediaQuery.of(context).size.height * 0.99,
              width: MediaQuery.of(context).size.width * 0.99,
              child: MazeShowWidget(
                childrenWidgets: widgetsNodes,
                parentWidget: parentText,
              ),
            ));
  } 

Then, when i tap a button, the captureFromLongWidget method is fired and it takes the screenshot. Usually it works as i get the image but i get the above error message in my console and often myLongWidget bounds overflow the screen (i get a RenderFlow error too) like i was using the simple capture() method to get the screenshot of a widget visible on the screen.

I tried to wrap my Builder inside a Material or Scaffold but nothing changes.

**Comment by Artico77** [comment]
update: i removed the SizedBox widget AND rebuilt the app, 
Now it looks like it works fine.
