### ISSUE TITLE
capture from long widget in version 1.3.0 

### ISSUE THREAD

**Issue by nikhil-viewzen** [SachinGanesh/screenshot#161]
I need to capture a long widget thats not rendered and I am using version 1.3.0 how do I do capturefromLongWidget

**Comment by laguierre** [comment]
I'd to know the same, if it's possible to screenshot a long widget in a finite ListView (around 20 items)

**Comment by ritheshSalyan** [comment]
Hi @nikhil-viewzen,

We have this API in version `2.1.0`. Please use that version.

**Comment by ritheshSalyan** [comment]
Closing issue. If you think it is incorrect please reopen the issue.
