### ISSUE TITLE
white screen screenshot not working its missing data because the screen shot background always black.

### ISSUE THREAD

**Issue by kw2019ltd** [SachinGanesh/screenshot#17]
![Screenshot_20200324-073549__01](https://user-images.githubusercontent.com/47334522/77392351-6207da00-6da3-11ea-83aa-ac4f4871f17a.jpg)

**Comment by kw2019ltd** [comment]
if i warp the widget with Card instead of Container its working fine with light mode(note: in dark mode its working with both Card and Container)

**Comment by mikechari** [comment]
This is also happening to me, tried to wrap the Screenshot with a Card but didn't, work neither on dark or light mode on my phone, any fixes to this?

Thanks in advance

**Comment by ritheshSalyan** [comment]
@kw2019ltd Are you using any background color in theme?

**Comment by Marcusjnr** [comment]
I had this same issue to, I solved it by giving the container a background color

**Comment by YouSour** [comment]
i got this problem too, anyone solve it , yet ?

**Comment by ebot64** [comment]
I encountered this issue after implementing both dark and light themes in my app. 

In a similar screenshot [package](https://pub.dev/packages/vocsy_esys_flutter_share) with same issue, suggestion was to wrap the widget with white background container. While this may work for light theme, it defeats the purpose for dark theme. See issue [here](https://github.com/esysberlin/esys-flutter-share/issues/22)

In my case, when app is in dark theme, screenshot image appears as expected without including the white background container; but in light theme, screenshot image appears blackened. If I include the container with white background, the blackened screenshot switches between the themes --> screenshot image now appears okay in light theme and becomes blackened in dark theme. 

My work around is to check the current theme and use Colors.transparent for dark theme and Colors.white for light theme as below. This works in whatever theme mode.
```
Screenshot(
  controller: screenshotController,
  child: Container(
    color: isDarkModeEnabled
        ? Colors.transparent
        : Colors.white,
    child: WidgetToBeShared(),
  )
)
```

**Comment by ritheshSalyan** [comment]
Wrap your widget with the container and provide color to it. This will change the background color of your widget. 

Closing this issue. If you think it is incorrect please feel free to reopen.
