### ISSUE TITLE
The argument type 'Null Function(Uint8List)' can't be assigned to the parameter type 'FutureOr<dynamic> Function(Uint8List?)'. 

### ISSUE THREAD

**Issue by lucasjinreal** [SachinGanesh/screenshot#172]
The argument type 'Null Function(Uint8List)' can't be assigned to the parameter type 'FutureOr<dynamic> Function(Uint8List?)'.

**Comment by ritheshSalyan** [comment]
Hi @lucasjinreal,

It looks like there is some type mismatch in your code. Please share some part of your code so that we can help you in resolving that.

**Comment by aryan1107** [comment]
same issue here

<img width="1048" alt="Screenshot 2024-04-24 at 8 43 30 PM" src="https://github.com/SachinGanesh/screenshot/assets/31214277/4cc547c9-877d-4a29-9dfe-54f729ef2db0">
