### ISSUE TITLE
Take a screenshot of Surface view on Android

### ISSUE THREAD

**Issue by agungsb** [SachinGanesh/screenshot#18]
Hi,

Is it possible to make it able to take a screen shot of surface view on Android?

It only generate a blank screen as of now.

**Comment by ritheshSalyan** [comment]
Currently due to https://github.com/flutter/flutter/issues/83856 we cannot capture Platfrom Views

**Comment by ritheshSalyan** [comment]
Closing in favour of https://github.com/SachinGanesh/screenshot/issues/62
