### ISSUE TITLE
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/screenshot-2.4.0/lib/screenshot.dart:165:9: Error: No named parameter with the name 'logicalConstraints'.

### ISSUE THREAD

**Issue by tareqalhammoodi** [SachinGanesh/screenshot#182]
Hey, 
I've been getting this error for the past two days when I run my app, I tried updating the package to the last version (screenshot: ^2.4.0) but it didn't help, also checked the previous issues but didn't find anything related. Any help please?

Error Message: 
<img width="1155" alt="Screenshot 2024-05-14 at 11 31 29" src="https://github.com/SachinGanesh/screenshot/assets/44919941/49d985b9-b212-4a8a-adfe-c80631992a07">

**Comment by ritheshSalyan** [comment]
Hi @tareqalhammoodi , Which version of flutter are you using? If you are using flutter version <=3.19 then consider using "[2.3.0](https://pub.dev/packages/screenshot/versions/2.3.0)" of `screenshot`. 

Version `2.4.0` is update for flutter >=3.22 .

**Comment by tareqalhammoodi** [comment]
ok thanks so much!
