### ISSUE TITLE
i have update 2.3.0 to 2.4.0 and getting this error .

### ISSUE THREAD

**Issue by vijayvaghela72** [SachinGanesh/screenshot#184]
<img width="1274" alt="Screenshot 2024-05-14 at 3 28 52 PM" src="https://github.com/SachinGanesh/screenshot/assets/61325761/b4d49a2c-1c1d-4072-a200-23b44626f41c">

**Comment by vijayvaghela72** [comment]
also i have try to downgrade this version in pubspect file but still facing this error .

**Comment by vijayvaghela72** [comment]
i've try


flutter clean 
flutter pub get 
flutter run

**Comment by vanlooverenkoen** [comment]
:( breaking changes on a minor version change. :(

**Comment by vijayvaghela72** [comment]
this kind of changes rely effect development process 

need to be a more professional !


please test small things and then update package in pub.dev :(

**Comment by ritheshSalyan** [comment]
Hi, If you are using flutter version <=3.19 then consider using "[2.3.0](https://pub.dev/packages/screenshot/versions/2.3.0)" of `screenshot`. 

Version `2.4.0` is update for flutter >=3.22 .

**Comment by vanlooverenkoen** [comment]
Please in the future use 3.0.0 when doing breaking changes. 

This is the documentation on how to do semantic versioning:
https://semver.org/

**Comment by vanlooverenkoen** [comment]
Also use the proper pubspec config to indicate that a version should only be used as of a specific version.

```bash
environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=3.22.0'
```

**Comment by ritheshSalyan** [comment]
@vanlooverenkoen  Ok,  Thank you for suggestions. I will consider your suggestions for future releases.

**Comment by ritheshSalyan** [comment]
We published 2 versions

- `2.5.0` : As a revert for release `2.4.0` with maximum constraint.
- `3.0.0` :  Major change with minimum flutter constraint ``` flutter: '>=3.22.0'```.

I hope this would solve version issues. closing this issue . If you think this is incorrect please consider reopening the issue.

**Comment by vijayvaghela72** [comment]
Thanks for update !

Version 3.0.0 is just awesome !
