### ISSUE TITLE
upgrade the package to support latest flutter version v3.22.1

### ISSUE THREAD

**Issue by xenSlayer** [SachinGanesh/screenshot#186]
## Version:

```
Flutter 3.22.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision a14f74ff3a (2 days ago) • 2024-05-22 11:08:21 -0500
Engine • revision 55eae6864b
Tools • Dart 3.4.1 • DevTools 2.34.3
```

## Error building the project:

```
size is not defined in ViewConfiguration(), package:flutter/src/rendering/view.dart
```

**Comment by ITApexGroup** [comment]
> ## Version:
> ```
> Flutter 3.22.1 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision a14f74ff3a (2 days ago) • 2024-05-22 11:08:21 -0500
> Engine • revision 55eae6864b
> Tools • Dart 3.4.1 • DevTools 2.34.3
> ```
> 
> ## Error building the project:
> ```
> size is not defined in ViewConfiguration(), package:flutter/src/rendering/view.dart
> ```

Yes, me too.

**Comment by ritheshSalyan** [comment]
Hi,
Which version of the screenshot package are you using?
Please use the screenshot version `screenshot: ^3.0.0`.
