### ISSUE TITLE
Is this working on web?

### ISSUE THREAD

**Issue by quetool** [SachinGanesh/screenshot#19]
I am trying to use this with flutter web but I think it might be not supported because I get an error:
```
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/scene_builder.dart:111:16
matrix4[0] == window.devicePixelRatio &&
           matrix4[5] == window.devicePixelRatio
is not true
```

**Comment by encrustace** [comment]
I'm having same error when trying to use it in flutter web.

**Comment by sashvoncurtis** [comment]
https://github.com/flutter/engine/pull/20750

**Comment by taeilyoon** [comment]
> [flutter/engine#20750](https://github.com/flutter/engine/pull/20750)
https://github.com/flutter/engine/pull/20750 has been merged. any updates?

**Comment by salime45** [comment]
In beta channel is working

**Comment by ritheshSalyan** [comment]
we have added support for web and windows. please update package to the latest version
