### ISSUE TITLE
Allow screenshots with specific dimensions

### ISSUE THREAD

**Issue by nikhilmufc7** [SachinGanesh/screenshot#22]
The plugin works pretty well, but when I export the image it is saved as a full page screenshot with the widget that I am taking screenshot of in center and black area on top and bottom. Is it possible to create dimensions that we can use to take screenshot like providing a specific height and width. Or cropping it to the specified dimensions before saving in gallery.

**Comment by jlnrrg** [comment]
From what I have gathered the `captureFromWidget` method uses the `ui.window.physicalSize` which is probably bc it also uses `ui.window`. 
I am unsure, if this can be changed, but will try a thing or two.

This is what I've tested so far
- [x] wrapping the method and/or the widget in a seperate `MediaQuery(child: child)`
- [x] wrapping the method and/or the widget in a seperate `Theme(child: child)`
- [x] wrapping the widget widget in a `Sizedbox(height: 100, width: 100, child: child)`
- [ ] editing the method myself

**Comment by jlnrrg** [comment]
@bobatsar I solved it by only using fixed sized components and then calculating the width and height based on the amount.
I know this does not answer your question unfortunately :disappointed:

**Comment by ritheshSalyan** [comment]
Please use latest version of plugin to set target size. Closing this issue
