### ISSUE TITLE
`capture()` method does not work on Windows

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [SachinGanesh/screenshot#27]
`capture()` method does not work on Windows because the paths in windows use `\` while your package is using `/` which works for other platforms. I would suggest adding a check to see if the platform is windows or not and add the path separator accordingly

**Comment by usarthurchoi** [comment]
for example, capture will get the following exception

flutter: FileSystemException: Cannot open file, path = 'C:\Users\---\Documents/2020-12-11T17:37:46.917156.png' (OS Error: The filename, directory name, or volume label syntax is incorrect.

**Comment by ritheshSalyan** [comment]
Please update package to the latest version. this issue has been fixed in the latest version.
