### ISSUE TITLE
Image in gallery picture is black

### ISSUE THREAD

**Issue by kmochimaru** [SachinGanesh/screenshot#29]
```
      this._screenshotOwner
                  .capture(delay: Duration(milliseconds: 10), pixelRatio: 3)
                  .then((File captureImage) async {
                Map<PermissionGroup, PermissionStatus> permissionResult = await PermissionHandler().requestPermissions([PermissionGroup.storage]);
                if (permissionResult[PermissionGroup.storage] != PermissionStatus.granted) throw "Permission Denied";
                final result = await ImageGallerySaver.saveImage(captureImage.readAsBytesSync());
                print(result);
              });
```

**Comment by chenkaiC4** [comment]
i get the same issue. did you solved?

**Comment by am10code** [comment]
@chenkaiC4 @kmochimaru 
hi guys

Just try to use Container with background color, then wrap that container into the Screensot widget - it works

**Comment by vikskod** [comment]
This will solve your problem

**Comment by vikskod** [comment]
Do not forget to add backgroundColor: Colors.white
I had same issue. This will solve your problem

BarcodeWidget(
                        backgroundColor: Colors.white,
                        barcode: Barcode.qrCode(),
                        color: Colors.black,
                        data: txtController.text ?? '',
                        width: 250,
                        height: 250,
                      )

**Comment by congfandi** [comment]
I give color white to my container insider screenshoot controller.. its works guys
