### ISSUE TITLE
path_provider version

### ISSUE THREAD

**Issue by neiljaywarner** [SachinGanesh/screenshot#3]
can you update that please

**Comment by SachinGanesh** [comment]
Currently this plugin is using the latest version of path_provider (v0.5.0).

**Comment by neiljaywarner** [comment]
Currently meaning what? I got this error Saturday w 002. Did you update screenshot to a v003?
(Sorry.. From phone and in a hurry)

**Comment by SachinGanesh** [comment]
Please check commit: 32b47de. Updated 13 days ago

**Comment by SachinGanesh** [comment]
Updated to version: path_provider: ^1.1.0
