### ISSUE TITLE
in flutter web not working

### ISSUE THREAD

**Issue by wattamwarp** [SachinGanesh/screenshot#36]
screenshotController.capture().then((Uint8List image) {
                                                  //Capture Done
                                                  setState(() {
                                                    _imageFile = image;
                                                    print("the image file is "+_imageFile.toString());
                                                  });
                                                }).catchError((onError) {
                                                  print(onError);
                                                });

iam using this code its working fine in mobile(android+ios) but not working in web
throwing this error -- "Unsupported operation: toImage is not supported on the Web"

**Comment by elihaidv** [comment]
HI I wrote a post with a workaround about this error
https://elihaidv.medium.com/take-a-screenshot-with-flutter-for-web-739e52b45fec

Maybe it can be good idea to add this functionality to the package

**Comment by hyungtaecf** [comment]
Can someone explain to me why it says on pub.dev that it has support for the web, but it doesn't work? What works for the web then, and how to use it?

**Comment by wattamwarp** [comment]
Thanks

**Comment by ritheshSalyan** [comment]
This package Support Capturing screnshot on Web as well. Please use the latest Version on this package.

https://user-images.githubusercontent.com/44966372/125052581-c1d1e380-e0c1-11eb-8dbe-8cc44e6926b3.mp4

**Comment by thKali** [comment]
> Can someone explain to me why it says on pub.dev that it has support for the web, but it doesn't work? What works for the web then, and how to use it? Even if it is not able to download, Is there a way to capture and send it to an email, for example?

only works with canvas rendering,  the method toImage() doesn't work on HTML Renderer,
