### ISSUE TITLE
PaintContext does not support embedding

### ISSUE THREAD

**Issue by UjjwaRaijada** [SachinGanesh/screenshot#37]
I am trying to take screenshot of web page (WebView) on my app. It is giving below error.

E/flutter (10118): [ERROR:flutter/flow/layers/platform_view_layer.cc(25)] Trying to embed a platform view but the PrerollContext does not support embedding
E/flutter (10118): [ERROR:flutter/flow/layers/platform_view_layer.cc(40)] Trying to embed a platform view but the PaintContext does not support embedding

**Comment by ritheshSalyan** [comment]
Closing in favour of https://github.com/SachinGanesh/screenshot/issues/62
