### ISSUE TITLE
Capture Widget without context

### ISSUE THREAD

**Issue by leeprobert** [SachinGanesh/screenshot#38]
I have to add an image to my MapBox map so I want to build a Widget, capture it as an image, and then send it into the map. The Widget is not going to be rendered on-screen at all in the context. Here's my code for creating the image and passing it to the MapBoxController:

```
Future<void> _addImageFromPOI(MapboxMapController controller, POI poi) async {
    // Create an image from the POI icon information
    // Needs to build a widget and then draw an image of it for use on the map
    // Uint8List _imageFile;
    ScreenshotController screenshotController = ScreenshotController();
    POIWidget widget = POIWidget(poi: poi);
    Screenshot(
      controller: screenshotController,
      child: widget,
    );
    await screenshotController.capture().then((Uint8List image) {
      controller.addImage(poi.docId, image);
      controller.addSymbol(
        SymbolOptions(
          geometry: LatLng(poi.latitude, poi.longitude),
          iconImage: poi.docId,
        ),
      );
    }).catchError((onError) {
      print(onError);
    });
  }
```

... and I am getting an error:

`The method 'findRenderObject' was called on null.` - I suspect that this is because the Widget is not being rendered on the context. Is this correct?

**Comment by ritheshSalyan** [comment]
Yes. that is correct. Currently, we are using the Repaint boundary to capture the screenshot. This requires the rendering of the widget in order to capture the screenshot.
