### ISSUE TITLE
Can not take screenshot of Whole list view

### ISSUE THREAD

**Issue by WorthPly** [SachinGanesh/screenshot#4]
Hello,

I have 10 items in a list and if they can not visible in screen they are not showing in screenshot also. how can i capture screenshot for whole list of data.

**Comment by SachinGanesh** [comment]
I tested and confirmed. It is possible to take screenshot of the whole list

**Comment by jagan999** [comment]
I am using ListView.builder within a Container and it doesn't work. It only exports the visible part of the ListView. Can you pl check?

**Comment by GENL** [comment]
Same for me. I'm using a "for loop" inside of the SingleChildScrollView.

**Comment by laxkarparas1** [comment]
how to take screenshot of  whole list from it's captureFromWidget() method ?? 
any suggestion..

i'm taking screenshot from capture() method it's working perfectly and returning the whole list screenshot but when i'm taking screenshot from captureFromWidget() it's return only device size screenshot not whole list ..

**Comment by yy1300326388** [comment]
https://stackoverflow.com/a/64374568/4501068
