### ISSUE TITLE
Can I take desktop screenshot (not want to take widget screenshot)

### ISSUE THREAD

**Issue by rupamking1** [SachinGanesh/screenshot#40]
Can I take desktop screenshot (not want to take widget screenshot), how?

**Comment by Babwenbiber** [comment]
Do you mean a screenshot of the full screen?

I was looking for the same.
I managed to do this by embedding my complete Page into a Screenshot.

However, there is a non deterministic behavior when the widgets don't fit into the page.

I think this definitely needs to be elaborated.

**Comment by SachinGanesh** [comment]
Hi, taking desktop screenshot (full screen - aka outside of the app) is not currently supported.

**Comment by ashwin31** [comment]
Hi @SachinGanesh  is it possible now or it's impossible technically?
