### ISSUE TITLE
Convert Uint8List to File

### ISSUE THREAD

**Issue by tonyteo72** [SachinGanesh/screenshot#41]
I am using the previous version 0.2.0 of screenshot and it support capture as File. With the new 0.3.0, it is now Uint8List.
How do I convert Uint8List into File ?

**Comment by nhien021299** [comment]
Try this man, it work for me:
await _screenshotController.capture(delay: const Duration(milliseconds: 10)).then((Uint8List image) async {
      if (image != null) {
        final directory = await getApplicationDocumentsDirectory();
        final imagePath = await File('${directory.path}/image.png').create();
        final Uint8List pngBytes = image.buffer.asUint8List();
        await imagePath.writeAsBytes(pngBytes);
        await Share.shareFiles([imagePath.path]);
      }
    });

**Comment by jxstxn1** [comment]
> Try this man, it work for me:
> await _screenshotController.capture(delay: const Duration(milliseconds: 10)).then((Uint8List image) async {
> if (image != null) {
> final directory = await getApplicationDocumentsDirectory();
> final imagePath = await File('${directory.path}/image.png').create();
> final Uint8List pngBytes = image.buffer.asUint8List();
> await imagePath.writeAsBytes(pngBytes);
> await Share.shareFiles([imagePath.path]);
> }
> });

I recommend a non-static filename, because the static one can create issues.
Generate a filename with a function like this:
 `String fileName = DateTime.now().microsecondsSinceEpoch.toString();`
With this you have a non-static filename. 
Now assign it at the save point:
`final imagePath = await File('${directory.path}/$fileName.png').create();`

**Comment by stephanie-finch** [comment]
What types of issues happen when you use a static file name?

**Comment by stephanie-finch** [comment]
> I recommend a non-static filename, because the static one can create issues.

What types of issues happen when you use static filenames?

**Comment by EA-YOUHOU** [comment]
This should be added to the package documentation :)
