### ISSUE TITLE
Screenshot is blurred on iPad Pro 9.7 

### ISSUE THREAD

**Issue by mikron123** [SachinGanesh/screenshot#43]
I'm trying to capture a screenshot of a drawing. On the phone is works great.
On an iPad pro iOS 14.4 (didn't try others) it is very blurred. Trying different pixel ratio parameters doesn't seem to help.

Using the latest version of Screenshot.

**Comment by SachinGanesh** [comment]
Calculate the pixelRatio like this

```dart
double pixelRatio = MediaQuery.of(context).devicePixelRatio;
```

**Comment by mikron123** [comment]
Did you try this with an iPad and it fixed the blurriness?

**Comment by mikron123** [comment]
> Calculate the pixelRatio like this
> 
> ```dart
> double pixelRatio = MediaQuery.of(context).devicePixelRatio;
> ```

Still terrible.

**Comment by uzumakinaruto123** [comment]
Blur on all iOS devices. Specifying pixel ratio doesn't help. Android works great.

**Comment by uzumakinaruto123** [comment]
Apparently, Screenshot was not the culprit here.  When GallerySaver https://github.com/CarnegieTechnologies/gallery_saver is saving file from path Screenshot has emitted it is blurred.  Used Photomanager package to save file instead and it worked.

**Comment by ritheshSalyan** [comment]
@uzumakinaruto123 If this issue is cleared you can close this.

**Comment by uzumakinaruto123** [comment]
> @uzumakinaruto123 If this issue is cleared you can close this.

You tagged the wrong person. Not the author of this issue.
