### ISSUE TITLE
PDFTron view cannot capture in screenshot.

### ISSUE THREAD

**Issue by jemaineosia** [SachinGanesh/screenshot#46]
Hi,

We are using PDFTron for viewing PDF in Flutter but when we use the screenshot, it is not showing. The rest of the screen can capture except for the pdftron documentview.

**Comment by SachinGanesh** [comment]
Native Views are not supported as of now

**Comment by jemaineosia** [comment]
> Native Views are not supported as of now

I see. Thank you very much! :)
