### ISSUE TITLE
How do I capture components that are out of screen scope and invisible

### ISSUE THREAD

**Issue by elMan-L** [SachinGanesh/screenshot#51]
For example, a ListView or a large artboard。

**Comment by canturkay** [comment]
Hi, did you find any solutions for this?

**Comment by JMApps** [comment]
Actual question

**Comment by venky9885** [comment]
Waiting 

- [ ]

**Comment by SachinGanesh** [comment]
Use `captureFromWidget`

**Comment by JMApps** [comment]
> Use `captureFromWidget`

This does not solve the problem

**Comment by SachinGanesh** [comment]
`captureFromWidget` takes screenshot of a widget that is not present in the screen. May I know what issue you are facing?

**Comment by JMApps** [comment]
> `captureFromWidget` takes screenshot of a widget that is not present in the screen. May I know what issue you are facing?

Yes, you're right, it takes a screenshot of the widget we pass to it. And if the length of this widget is longer than displayed on the screen, then the screenshot is truncated.

**Comment by daybson** [comment]
How do I use it to take a screenshot of itens not visible in a listview, when the listview is too long?

**Comment by junlandroid** [comment]
How do I use it to take a screenshot of itens not visible in a listview, when the listview is too long? @SachinGanesh help

**Comment by junlandroid** [comment]
reset logicalSize , This works, but I don’t know why it’s multiplied by 2.

`    // Size logicalSize = ui.window.physicalSize / ui.window.devicePixelRatio;
    Size logicalSize = (_widgetHeight == null
            ? ui.window.physicalSize
            : Size(750, _widgetHeight! * 2)) /
        ui.window.devicePixelRatio;
    // Size imageSize = ui.window.physicalSize;
    Size imageSize = (_widgetHeight == null)
        ? ui.window.physicalSize
        : Size(750, _widgetHeight! * 2);`

**Comment by junlandroid** [comment]
reset logicalSize , This works, but I don’t know why it’s multiplied by 2.
```
  // Size logicalSize = ui.window.physicalSize / ui.window.devicePixelRatio;
    Size logicalSize = (_widgetHeight == null
            ? ui.window.physicalSize
            : Size(750, _widgetHeight! * 2)) /
        ui.window.devicePixelRatio;
    // Size imageSize = ui.window.physicalSize;
    Size imageSize = (_widgetHeight == null)
        ? ui.window.physicalSize
        : Size(750, _widgetHeight! * 2);
```

**Comment by ritheshSalyan** [comment]
Closing in favor of https://github.com/SachinGanesh/screenshot/issues/25#issuecomment-877019128
