### ISSUE TITLE
Animations capture

### ISSUE THREAD

**Issue by salime45** [SachinGanesh/screenshot#6]
Hi

I am working with animations in my app

there are any way to convert the animations in video o gif ?

**Comment by hbock-42** [comment]
Hi, I did this here => https://github.com/hbock-42/platinette/blob/master/packages/vinyl_viewer/lib/widgets/recordable_rotating_macaron.dart
not very clean, if you want to take a look.

I am working on doing this a bit cleaner, and will try to use SachinGanesh screenshot plugging.
If I do it successfully I may do a pull request here, but I am not sure this would be relevant since this package is called screenshot and not screenrecorder.

**Comment by SachinGanesh** [comment]
@hbock-42 Thanks for working on the animation functionality. I would prefer this to be a separate package, as all may not require this functionality.

**Comment by sumitgohil** [comment]
@hbock-42 Hi, it's great to see you working on this feature. You said if you're trying to clean it, except this is your code working? 

I can see you've forked screenshot library, are you planning on creating a screen recorder library? 

I was going through your code, but you're using bloc pattern and that kinda confused me a bit. 😅

**Comment by hbock-42** [comment]
@sumitgohil Sorry did not have a lots of time lately. I still had the time to use SachinGanesh screenshot library to record animation. I Created a recording widget here https://github.com/hbock-42/platinette_stacked/blob/master/packages/platinette_app/lib/ui/widgets/widget_recorder/widget_recorder.dart
But it is not straightforward to use it, you can check where I use it here https://github.com/hbock-42/platinette_stacked/blob/master/packages/platinette_app/lib/ui/widgets/recordable_vinyl/recordable_vinyl.dart

Keep in mind I am working on this app so it is changing frequently :) I  just linked you this so you can find and example (without bloc this time)

**Comment by rdcoder33** [comment]
> Hi, I did this here => https://github.com/hbock-42/platinette/blob/master/packages/vinyl_viewer/lib/widgets/recordable_rotating_macaron.dart
> not very clean, if you want to take a look.
> 
> I am working on doing this a bit cleaner, and will try to use SachinGanesh screenshot plugging.
> If I do it successfully I may do a pull request here, but I am not sure this would be relevant since this package is called screenshot and not widget recorder.

waiting for it, it will help many developers.

**Comment by hbock-42** [comment]
@rdcoder33  @sumitgohil @salime45 
I made a dirty package of what I was working on https://pub.dev/packages/widget_record
Very early version, I am sorry I am very busy right now so I cannot do something very clean but I still manage to do this for you, have fun

**Comment by rdcoder33** [comment]
> @rdcoder33 @sumitgohil @salime45
> I made a dirty package of what I was working on https://pub.dev/packages/widget_record
> Very early version, I am sorry I am very busy right now so I cannot do something very clean but I still manage to do this for you, have fun

@hbock-42  Thanks, man! Really Appreciated. I am also currently learning Native Code and how to work with plugins, once done I will surely help you to clean this.
