### ISSUE TITLE
ScreenShot Share not working 

### ISSUE THREAD

**Issue by neelayak** [SachinGanesh/screenshot#68]
As given in the example for sharing the captured image
`await _screenshotController.capture(delay: const Duration(milliseconds: 10)).then((Uint8List image) async {
      if (image != null) {
        final directory = await getApplicationDocumentsDirectory();
        final imagePath = await File('${directory.path}/image.png').create();
        await imagePath.writeAsBytes(image);

        /// Share Plugin
        await Share.shareFiles([imagePath.path]);
      }
    });`
is throwing error 

> The argument type 'Future<Null> Function(Uint8List)' can't be assigned to the parameter type 'FutureOr<dynamic> Function(Uint8List?)

i tried to fix this but seems not working when trying to get the path as the method is not even called

**Comment by ritheshSalyan** [comment]
@neelayak I think problem is not with plugin but it is with usage. it is a null-safety issue.
Possible solutions are

1. Change 
```dart 
await _screenshotController.capture(delay: const Duration(milliseconds: 10)).then((Uint8List image) async {
.......
});
```

To 

```dart 
await _screenshotController.capture(delay: const Duration(milliseconds: 10)).then((Uint8List? image) async {
.......
});
```
2. change method of handling future like

```dart
Uint8List? image = await _screenshotController.capture(delay: const Duration(milliseconds: 10));
if (image != null) {
       final directory = await getApplicationDocumentsDirectory();
       final imagePath = await File('${directory.path}/image.png').create();
       await imagePath.writeAsBytes(image);

      /// Share Plugin
      await Share.shareFiles([imagePath.path]);
}

```

**Comment by erperejildo** [comment]
> @neelayak I think problem is not with plugin but it is with usage. it is a null-safety issue. Possible solutions are
> 
> 1. Change
> 
> ```dart
> await _screenshotController.capture(delay: const Duration(milliseconds: 10)).then((Uint8List image) async {
> .......
> });
> ```
> 
> To
> 
> ```dart
> await _screenshotController.capture(delay: const Duration(milliseconds: 10)).then((Uint8List? image) async {
> .......
> });
> ```
> 
> 2. change method of handling future like
> 
> ```dart
> Uint8List? image = await _screenshotController.capture(delay: const Duration(milliseconds: 10));
> if (image != null) {
>        final directory = await getApplicationDocumentsDirectory();
>        final imagePath = await File('${directory.path}/image.png').create();
>        await imagePath.writeAsBytes(image);
> 
>       /// Share Plugin
>       await Share.shareFiles([imagePath.path]);
> }
> ```

where are you getting getApplicationDocumentsDirectory() from?
