### ISSUE TITLE
Taking screenshot of cameraPreview

### ISSUE THREAD

**Issue by falconNeelay** [SachinGanesh/screenshot#71]
So i tried taking pic of a widget which is over the camerpreview and the screenshot is not working as it gives a black screen . Any solution for this i will love to help you guys

**Comment by ritheshSalyan** [comment]
Closing in favour of #62.  Currently ,Capturing Native view is not supported.

**Comment by MudasarRather** [comment]
@ritheshSalyan how we will deal the issue

**Comment by ritheshSalyan** [comment]
@MudasarRather We cannot capture screenshot of platform views, If you are using camera plugin then it has takeImage method you can make use of it.
