### ISSUE TITLE
Slow rendering speed after updating from 1.2.2 to 1.2.3

### ISSUE THREAD

**Issue by cream-cheeze** [SachinGanesh/screenshot#73]
After upgrading from 1.2.2 to 1.2.3 my code began to hangup.

I'm using the screenshot plugin for rendering widget to image this way:

```
var widget = MapTooltip(text: address);
final imgData = await screenshotController.captureFromWidget(widget, pixelRatio: 3.0);
```

My code hasn't been changed. With 1.2.2 it just flying, with 1.2.3 - performs very slowly.

What could be the issue?

**Comment by cream-cheeze** [comment]
Guess I found: default delay changed to 1 second. Should be noticed in the changelog.

Could you explain why is it done?

**Comment by ibrahimdevs** [comment]
@SachinGanesh  I'm in the same doubt. 
I read the issue: https://github.com/flutter/flutter/issues/22308 . As I understand, we only should wait to finish rendering widgets inside screenshot. (Like button click animation etc.)
https://github.com/flutter/flutter/issues/22308#issuecomment-424767901 

I'm using "captureFromWidget" method for non-visible widget, so I think we don't even need any delay here. Am I wrong?

Thanks,

**Comment by ritheshSalyan** [comment]
Closing this issue. If you think it is incorrect please reopen.
