### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(Invalid file path, null, null, null)

### ISSUE THREAD

**Issue by naeem-shah** [SachinGanesh/screenshot#74]
I am facing following error while trying to capture widgets.

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(Invalid file path, null, null, null)
E/flutter (  825): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
E/flutter (  825): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (  825): <asynchronous suspension>
E/flutter (  825): 
```

version: **screenshot: ^1.2.3**

flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1165], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] Connected device (3 available)

! Doctor found issues in 1 category.

**Comment by venky9885** [comment]
Share the code ,I will solve it
