### ISSUE TITLE
screenshot problem with color on android 

### ISSUE THREAD

**Issue by YouSour** [SachinGanesh/screenshot#78]
hi , i got some problem on android with screenshot , color image that screenshot not show as i expected **some part has a grey color and some part has a black color** this problem happen only on Android but IOS it works fine. how can i fix it ? thank in advance.

**Device :** 
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-09-23 at 08 44 32](https://user-images.githubusercontent.com/9318106/134444310-855bca8b-120c-4295-b293-9dd8f2c81cbc.png)

**Expected :**
![photo_2021-09-23 08 58 32](https://user-images.githubusercontent.com/9318106/134444403-dd52da0c-855c-4600-a5ae-2b5d351d3f12.jpeg)

**Result :**
![photo_2021-09-23 08 54 55](https://user-images.githubusercontent.com/9318106/134444507-fdeee25c-b238-474e-bf2e-d5cb3e59e677.jpeg)

**Comment by YouSour** [comment]
solved

**Comment by Kishan-Somaiya** [comment]
how did you solve it ? @YouSour

**Comment by YouSour** [comment]
@Kishan-Somaiya i set background color 😄
