### ISSUE TITLE
Directory usage is quite difficult to understand.

### ISSUE THREAD

**Issue by mg64775** [SachinGanesh/screenshot#8]
Please document somewhere that the App directory cannot be read from another app, this is by design and I understand this fully.  When the image is stored in the App directory(as suggested in your write-up) gMail app cannot attach the file. I would suggest to use the Temp directory for this instead of the App directory. Also with a mention about this intricate situation.

Mario

**Comment by ritheshSalyan** [comment]
you can pass the custom directory path to store the image in the latest version.
