### ISSUE TITLE
Capture from another thread

### ISSUE THREAD

**Issue by h3x4d3c1m4l** [SachinGanesh/screenshot#86]
Hi, for high speed capturing (for a "pixelflut" client) I would like to capture screenshots from another thread (e.g. using `Isolate`).

But when I invoke the capture method from the other thread, it throws
`Null check operator used on a null value`
on this line:
`var findRenderObject = this._containerKey.currentContext?.findRenderObject();`

Using the same `ScreenshotController` I can actually capture when invoking the capture method from `onPressed`.

Is there a way to keep capturing in a fast way?

**Comment by nhtdev1** [comment]
Any update?

**Comment by h3x4d3c1m4l** [comment]
hi, all

unfortunately I havent been able to solve it

i dont think it can be fixed the way i was hoping to fix it, because isolates cant access any data from other isolates and one has to explicitly share data between isolates

depending on your usecase, maybe you can export to RGBA of BGRA format (which should be pretty fast), then handover those bytes to another isolate to processes and export to png/jpeg

for my own project I combined the power of Rust (which has extremely fast libraries for JPEG encoding) and Flutter (which can call Rust libraries using ffi) in order to archieve the performance I need

**Comment by Somtobro** [comment]
Thanks for this
Although for my use case I was trying to screengrab 30 to 60 screenshots
per second to make a 30fps motion video on Android.
I'd check it out to see if it can be of help
Thanks again

**Comment by ritheshSalyan** [comment]
Hi, 

Due to the limitation of flutter, we cannot render widgets from another isolate. so as of now, we can't do this.

Closing this issue. If you think It is incorrect please reopen the issue
