### ISSUE TITLE
Images are not captured in the screenshot

### ISSUE THREAD

**Issue by dheeraj2dj** [SachinGanesh/screenshot#9]
I have been trying to capture a widget which has images in it, and unfortunately, images are not captured in the screenshot

**Comment by dheeraj2dj** [comment]
Found [this](https://api.flutter.dev/flutter/flutter_driver/FlutterDriver/screenshot.html) helpful, had a delay of 1 second and it worked!

**Comment by SachinGanesh** [comment]
Hi. there is already delay: parameter in capture method which does the same thing.

**Comment by clearloop** [comment]
Same issue, screenshots don't have background...
