### ISSUE TITLE
Web version, image screenshot FAIL

### ISSUE THREAD

**Issue by TimotheeR** [SachinGanesh/screenshot#93]
Hello everyone,

I implemented the "screenshot" package in the mobile version of my application, without problems.
On the other hand, in the web version, it is impossible to make a screenshot of an image.
Text Widget OK
Widget Icon OK
Widget Image.asset FAIL
Box Decoration(image: …) FAIL

Flutter 2.11.0 channel Master
Screenshot 1.2.3

Thank you

**Comment by Blackshires** [comment]
Hello,

Same issue here, working fine on mobile device, but unable to take screenshots from widget with image on the web version.

As TimotheeR say, it work with text, icons, ... but not with images.

Screenshot version 1.2.3

The strange thing is that it worked before i update my flutter version to the last one (channel master), i don't remember the previous version, i just go to another solution for my screenshots.

Thank you

**Comment by TimotheeR** [comment]
Hello,

For me with:
flutter run => screenshot OK, load image from firebase storage NOT OK
flutter run --web-renderer html => screenshot NOT OK , load image from firebase storage OK

I am using flutter version 2.10.3
