### ISSUE TITLE
Flutter Web, upload Uint8List to Firebase Storage

### ISSUE THREAD

**Issue by TimotheeR** [SachinGanesh/screenshot#97]
Hello,

My code below works like a charm with iOS or Android, but not with Web.
I tried lots of things without success.
Please, do you have a solution for uploading a screenshot in Firebase Storage?

Thank you

`  
  Reference reference = _storage.ref().child("fileName");
      UploadTask uploadTask = reference.putData(byte);
      TaskSnapshot snapshot = await uploadTask;
      String downloadUrl = await snapshot.ref.getDownloadURL();
`

**Comment by ritheshSalyan** [comment]
Closing in favour of https://github.com/SachinGanesh/screenshot/issues/97#issuecomment-1106603845. If you think this is incorrect feel free to reopen.

**Comment by zhangxiaobin-bruce** [comment]
> Hello @TimotheeR
> 
> Here are some things you might need to take care.
> 
> 1. Please use `canvaskit` renderer for your web. Because this plugin can capture screenshot only in `canvaskit`.
> 2. Before uploading image please check that you have the image as `Uint8List`.
> 3. Make sure that you have followed all steps from firebase storage plugin.
> 
> Hope it helps.

If this plugin can only support `canvaskit`, can you add some note to README.md?
